global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: :443

log:
  level: ERROR

api:
  insecure: false

ping:
  entryPoint: websecure

tracing:
  servicename: "tracing"
  jaeger:
    samplingParam: 1.0
    samplingServerURL: "http://jaeger:5788/sampling"
    samplingType: "const"
    localAgentHostPort: "jaeger:6831"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: "proxy"
    exposedByDefault: false
    defaultRule: Host(`{{ normalize .Name}}.traefik.me`)
  file:
    filename: "traefik_dynamic.yml"
    watch: true
