http:
  middlewares:
    secureHeaders:
      headers:
        browserxssfilter: true
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        stsSeconds: 5
        stsIncludeSubdomains: true
        forceSTSHeader: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        isDevelopment: true
  routers:
    api:
      rule: "Host(`lb.traefik.me`)"
      entrypoints: ["web","websecure"]
      service: "api@internal"
      tls: "true"

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  stores:
    default:
      defaultCertificate:
        certFile: /ssl/cert.pem
        keyFile: /ssl/privkey.pem
