{
 "title": "Jaeger",
 "description": "Dashboard for monitoring jaeger running in a k8s environment. Works with 1.9+. Feedbacks? Please send to luong.vo@employmenthero.com",
 "tags": [ "jaeger" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Jaeger Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spans Received/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_collector_spans_received_total[5m]))"
    }
   ]
  },
  {
   "title": "Average in-queue latency (sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jaeger_collector_in_queue_latency_sum / jaeger_collector_in_queue_latency_count"
    }
   ]
  },
  {
   "title": "Batch Size (spans)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jaeger_collector_batch_size" }
   ]
  },
  {
   "title": "Queue Length (Spans)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jaeger_collector_queue_length" }
   ]
  },
  {
   "title": "Spans Dropped/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jaeger_collector_spans_dropped_total[5m])"
    }
   ]
  },
  {
   "title": "Span save latency (sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jaeger_collector_save_latency_sum / jaeger_collector_save_latency_count"
    }
   ]
  },
  { "title": "Jaeger Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "jaeger_agent_thrift_udp_server_packets_processed/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_thrift_udp_server_packets_processed_total[5m])) by (protocol)"
    }
   ]
  },
  {
   "title": "avg(jaeger_agent_thrift_udp_server_packet_size)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(jaeger_agent_thrift_udp_server_packet_size) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_server_queue_size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(jaeger_agent_thrift_udp_server_queue_size) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_server_read_errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_thrift_udp_server_read_errors_total[5m])) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_server_packets_dropped/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_thrift_udp_server_packets_dropped_total[5m])) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_thrift_udp_t_processor_handler_errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_thrift_udp_t_processor_handler_errors_total[5m])) by (protocol)"
    }
   ]
  },
  {
   "title": "jaeger_agent_tchannel_reporter_batches_submitted/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_submitted_total[5m])) by (format)"
    }
   ]
  },
  {
   "title": "jaeger_agent_tchannel_reporter_spans_submitted/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_spans_submitted_total[5m])) by (format)"
    }
   ]
  },
  {
   "title": "avg(jaeger_agent_tchannel_reporter_batch_size)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "avg(jaeger_agent_reporter_batch_size) by (format)"
    }
   ]
  },
  {
   "title": "jaeger_agent_http_server_requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_http_server_requests_total[5m])) by (type)"
    }
   ]
  },
  {
   "title": "jaeger_agent_tchannel_reporter_batches_failures/sec",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_failures_total[5m])) by (format)"
    }
   ]
  },
  {
   "title": "jaeger_agent_tchannel_reporter_spans_failures/sec",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_spans_failures_total[5m])) by (format)"
    }
   ]
  },
  {
   "title": "jaeger_agent_http_server_errors/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_http_server_errors_total[5m])) by (source, status)",
     "legendFormat": "{{source}}.{{status}}"
    }
   ]
  },
  {
   "title": "total(jaeger_agent_collector_proxy)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jaeger_agent_collector_proxy_total) by (endpoint,protocol,result)"
    }
   ]
  },
  { "title": "Jaeger Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Average request latency (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "(jaeger_rpc_request_latency_sum / jaeger_rpc_request_latency_count)*1000"
    }
   ]
  },
  {
   "title": "Requests/min (All requests)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/traces\")",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/traces/-traceID-\")",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/traces/-traceID-\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/services/-service-/operations\")",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services/-service-/operations\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  },
  {
   "title": "Requests/min (endpoint=\"/api/services\")",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\"}[5m]))*60",
     "legendFormat": "All requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\",status_code=~\"2xx\"}[5m]))*60",
     "legendFormat": "2xx Requests (/min)"
    },
    {
     "expr": "sum(rate(jaeger_rpc_http_requests_total{endpoint=~\"/api/services\",status_code!=\"2xx\"}[5m]))*60",
     "legendFormat": "Non-2xx Requests (/min)"
    }
   ]
  }
 ]
}